# Generated by Django 2.2.3 on 2019-07-11 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('half_hour_count', models.PositiveIntegerField()),
                ('contract_type', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('apply_email', models.EmailField(max_length=254)),
                ('limit_date', models.DateField()),
                ('creation_date', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.School')),
            ],
        ),
    ]
