dist: xenial
language: python
python:
  - '3.7'

branches:
  only:
    - /^release-.*$/
    - /^fix-.*$/

install:
  - 'pip install pipenv'
  - 'pipenv install --dev'

env:
  - DJANGO_SETTINGS_MODULE="core.settings"

services:
  - postgresql

script:
- 'pytest'
